### ISSUE TITLE
Bug:can't get correct source Tables when subQuery exists  'join on' multi_condition and use `()' package these multi_conditions

### ISSUE THREAD

**Issue by Eric1314Su** [reata/sqllineage#250] opened 2022-04-29 05:15 UTC
DEMO:
$ cat test.sql 
>>
insert overwrite table working.ad_cnt_w
select distinct * from (
select
    date_sub( COALESCE ( b.last_dt , date_sub (to_date('${CURRENT_DAY}') , -3 ) )  , -3 )     as event_dt
   ,stg.ad_id
   ,stg.type_id
   ,to_date('snpt_dt) as snpsht_dt
   ,stg.sts_value -  coalesce( a.ad_cnt_total,0 ) as incrmnt
from
v_work as stg
cross join
v_lwed b
left join
v_act as a
on  (stg.ad_id=a.ad_id and  stg.type_id=a.type_id)
) ;

$ sqllineage -f  test.sql  
>>
Source Tables:
    
Target Tables:
    working.ad_cnt_w

**Comment by cm-hirano-shigetoshi** [comment] 2022-05-03 15:18
I had the same issue and I made a minimum example.

```
with x as (
    select *
    from src_table_a
    join src_table_b
    on (true)
)
insert into dst_table
select * from x
```

```
$ sqllineage -vf aaa.sql
Statement #1: with x as (    select *    from src_table_a    joi...
    table read: []
    table write: [Table: <default>.dst_table]
    table cte: [SubQuery: x]
    table drop: []
    table rename: []
==========
Summary:
Statements(#): 1
Source Tables:

Target Tables:
    <default>.dst_table
```

The following works correctly.

```
with x as (
    select *
    from src_table_a
    join src_table_b
    on true
)
insert into dst_table
select * from x
```

**Comment by reata** [comment] 2022-05-08 11:08
This is a duplicate of #233 and is already fixed in master branch. I'll release a v1.3.5 within next two days.

**Closed by reata** 2022-05-08 11:08 UTC

**Comment by Eric1314Su** [comment] 2022-06-17 12:18
thank for your test



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/03/2022 23:18 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [reata/sqllineage] Bug:can't get correct source Tables when subQuery exists 'join on' multi_condition and use `()' package these multi_conditions (Issue #250) |

I had the same issue and I made a minimum example.

with x as (
    select *
    from src_table_a
    join src_table_b
    on (true)
)
insert into dst_table
select * from x

$ sqllineage -vf aaa.sql
Statement #1: with x as (    select *    from src_table_a    joi...
    table read: []
    table write: [Table: <default>.dst_table]
    table cte: [SubQuery: x]
    table drop: []
    table rename: []
==========
Summary:
Statements(#): 1
Source Tables:

Target Tables:
    <default>.dst_table


The following works correctly.

with x as (
    select *
    from src_table_a
    join src_table_b
    on true
)
insert into dst_table
select * from x
