### ISSUE TITLE
sql with more than one source tables sometimes has incorrect results?

### ISSUE THREAD

**Issue by nickhuang1996** [reata/sqllineage#333] opened 2023-03-06 05:36 UTC
Sorry for this problem, but if statement is like: :
```
insert into table_A
(
       x
      ,y
)
SELECT
      B.xb
      ,B.yb
FROM table_b B
;

 insert into table_A
(
       x
      ,y
)
SELECT
      C.xc
      ,C.yc
FROM table_c C
;
```

The results should be:
A.x <- B.xb
A.y <- B.yb
A.x <- C.xc
A.y <- C.yc
but the real results is :
A.x <- B.xb
A.y <- B.yb
A.xc <- C.xc
A.yc <- C.yc
Only the result of the first stmt is right.
Maybe this problem will lead to wrong results.

Then I add AS and solve this prolem:
```
 insert into table_A
(
       x
      ,y
)
SELECT
      B.xb AS x
      ,B.yb AS y
FROM table_b B
;

 insert into table_A
(
       x
      ,y
)
SELECT
      C.xc AS x
      ,C.yc AS y
FROM table_c C
;
```
The results now is right:
A.x <- B.xb
A.y <- B.yb
A.x <- C.xc
A.y <- C.yc

**Comment by reata** [comment] 2023-03-07 12:50
This is a duplicate of #212 . We don't officially support this feature for the moment. Please watch that issue for any update.

**Closed by reata** 2023-03-07 12:50 UTC
Labels: duplicate
