### ISSUE TITLE
Export data lineage in JSON

### ISSUE THREAD

**Issue by ArtemSamoilov** [reata/sqllineage#363] opened 2023-04-25 06:53 UTC
Hello!

The feature #299 to export data lineage in JSON could save a lot of work for our project. I have seen the open pull request for that, and want to ask if the feature is planned to be a part of any upcomig release.

Thanks for the work you are doing :)

**Comment by reata** [comment] 2023-04-25 13:26
Close as this is a duplicate of #298. Please comment with your use case there. The current PR won't be merged as that is not designed well.

**Closed by reata** 2023-04-25 13:26 UTC
Labels: duplicate
